// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcgbpecsuoxgupafoymb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZ2JwZWNzdW94Z3VwYWZveW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTA2NjQsImV4cCI6MjA2MzM4NjY2NH0.Lyq3gNO5PmwGu9EmGs6eTu6vGKD90_egg1ftoeQtWaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);